spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/diagnostic_lab
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  servlet:
    context-path: /api

app:
  jwt:
    secret: your-256-bit-secret-key-here
    expiration: 86400000 # 24 hours in milliseconds
  file:
    upload-dir: ./uploads/reports

logging:
  level:
    org.springframework.security: INFO
    com.isuzumahub.diagnostic: DEBUG
